export const ARCHITECTURE_ICONS = {
  generic: null,
  teams: "/ms-icons/m365/teams-chat.svg",
  microsoft365: "/ms-icons/m365/m365-cloud.svg",
  copilotStudio: "/ms-icons/power-platform/copilot-studio.svg",
  powerAutomate: "/ms-icons/power-platform/power-automate.svg",
  powerPlatform: "/ms-icons/power-platform/power-platform.svg",
  dataverse: "/ms-icons/power-platform/dataverse.svg",
  sharePoint: "/ms-icons/m365/sharepoint.svg",
  documents: "/ms-icons/m365/m365-document.svg",
  foundry: "/ms-icons/azure/microsoft-foundry.svg",
  foundryAgent: "/ms-icons/azure/foundry-agent-service.svg",
  foundryModels: "/ms-icons/azure/foundry-models.svg",
  azureOpenAI: "/ms-icons/azure/azure-openai.svg",
  azureML: "/ms-icons/azure/azure-machine-learning.svg",
  aiSearch: "/ms-icons/azure/azure-ai-search.svg",
  blobStorage: "/ms-icons/azure/storage-account.svg",
  azureSQL: "/ms-icons/azure/azure-sql.svg",
  appService: "/ms-icons/azure/app-services.svg",
  functions: "/ms-icons/azure/function-apps.svg",
  containerApps: "/ms-icons/azure/container-apps.svg",
  aks: "/ms-icons/azure/aks.svg",
  logicApps: "/ms-icons/azure/logic-apps.svg",
  apiManagement: "/ms-icons/azure/api-management.svg",
  frontDoor: "/ms-icons/azure/front-door.svg",
  waf: "/ms-icons/azure/waf.svg",
  entra: "/ms-icons/entra/entra-id.svg",
  externalIdentity: "/ms-icons/azure/external-identities.svg",
  managedIdentity: "/ms-icons/azure/managed-identities.svg",
  keyVault: "/ms-icons/azure/key-vault.svg",
  appInsights: "/ms-icons/azure/application-insights.svg",
  monitor: "/ms-icons/azure/azure-monitor.svg",
  logAnalytics: "/ms-icons/azure/log-analytics.svg",
  privateLink: "/ms-icons/azure/private-link.svg",
  vnet: "/ms-icons/azure/virtual-network.svg",
  fabricAgent: "/ms-icons/fabric/data-agent.svg",
  fabric: "/ms-icons/fabric/fabric.svg",
  lakehouse: "/ms-icons/fabric/lakehouse.svg",
  warehouse: "/ms-icons/fabric/warehouse.svg",
  oneLake: "/ms-icons/fabric/onelake.svg",
  semanticModel: "/ms-icons/fabric/semantic-model.svg",
  powerBI: "/ms-icons/fabric/power-bi.svg"
} as const;

export type ArchitectureIcon = keyof typeof ARCHITECTURE_ICONS;
