export const RECOMMENDATION_MAX_ATTEMPTS = 2;
export const AI_REASONING_EFFORTS = ["low", "medium", "high", "xhigh"] as const;
export const MAXIMUM_REASONING_EFFORT = "xhigh" as const;
export const ARCHITECT_REQUEST_TIMEOUT_MS = 300_000;
export const REVIEW_REQUEST_TIMEOUT_MS = 90_000;
export const RECOMMENDATION_TIMEOUT_MS = RECOMMENDATION_MAX_ATTEMPTS * ARCHITECT_REQUEST_TIMEOUT_MS;
export const RECOMMENDATION_CLIENT_TIMEOUT_MS = RECOMMENDATION_TIMEOUT_MS + 10_000;
export const REVIEW_CLIENT_TIMEOUT_MS = REVIEW_REQUEST_TIMEOUT_MS + 10_000;
